### PR TITLE
CLI implementation

### LINKED ISSUE #11: Implement Application CLI
## Context

In order for user to use the note application it should have a command line interface (cli) implemented via java scanner (`java.utils.Scanner`).

## Interface

```mermaid
flowchart TD
    subgraph mainMenu
        S[Start] --> M[Show Menu]
        M --> I{User selects option}
    end

    subgraph exit
        direction TB
        I -->|exit| E[Exit application]
    end

    subgraph addNote
        I -->|add| An[Enter note name]
        An --> Ac[Enter note content]
        Ac --> As[Save note]
        As --> M
    end

    subgraph modifyNote
        I -->|modify| Bn[Enter note id to modify]
        Bn --> Be{Note exists?}
        Be -->|No| BeNo[Error: Note not found] --> M
        Be -->|Yes| BeYes[Enter new content]
        BeYes --> Bu[Update note]
        Bu --> M
    end

    subgraph deleteNote
        I -->|delete| Dn[Enter note id to delete]
        Dn --> De{Note exists?}
        De -->|Yes| DeYes[Note found] --> Dd[Delete note]
        De -->|No| DeNo[Error: Note not found] --> M
        Dd --> M
    end

    subgraph searchNote
        I -->|search| Sn[Enter note name]
        Sn --> Se{Matches found?}
        Se -->|No| SeNo[Error: No results found] --> M
        Se -->|Yes| SeYes[Display matching notes]
        SeYes --> M
    end

    subgraph printNotes
        I --> |print| Pp[Print all notes]
    end
```

### PR DESCRIPTION
**Pull request by Le4aAs**

### CODE REVIEW

File: Main.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+        }
+
+        for (String title : notes.keySet()) {
+            System.out.println("Title: " + title);
+            System.out.println("Content: " + notes.get(title));
+        }
+    }
+
+    static void searchNote() {
+        System.out.print("Enter note name: ");
```
Comment (0wlie22) [inline Main.java]: change for Id (as integer)

File: Main.java [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+
+        System.out.print("Enter note content: ");
+        String content = scanner.nextLine();
+
+        notes.put(name, content);
+        System.out.println("Note saved.");
+    }
+
+    static void deleteNote() {
+        System.out.print("Enter note name to delete: ");
```
Comment (0wlie22) [inline Main.java]: change for id (as integer)

File: Main.java [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        if (notes.containsKey(name)) {
+            notes.remove(name);
+            System.out.println("Note deleted.");
+        } else {
+            System.out.println("Error: Note not found");
+        }
+    }
+
+    static void modifyNote() {
+        System.out.print("Enter note name to modify: ");
```
Comment (0wlie22) [inline Main.java]: change to id (as integer)

**Comment by 0wlie22** [comment]
please move it here: app/src/main/java/memoir/App.java

**Review by 0wlie22 — DISMISSED** [review]

**Review by ayselabiyeva — APPROVED** [review]

**Review by 0wlie22 — APPROVED** [review]
